./bin/kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --create --topic imp --partitions 3 --replication-factor 3
./bin/kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --create --topic clk --partitions 3 --replication-factor 3
./bin/kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --create --topic track --partitions 3 --replication-factor 3


#详情
bin/kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --describe --topic clk

#生产
./bin/kafka-console-producer.sh --broker-list 127.0.0.1:9092 --topic clk
#消费
./bin/kafka-console-consumer.sh --bootstrap-server 127.0.0.1:9093 --topic clk --from-beginning
